name: Feature request
description: Tell us about a level, a mechanic or an improvement that you want.
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: The idea
      description: Tell us what you want to see. Tell us how it makes the game better.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Other solutions that you examined
